// Reads a JSON file of objects generated by LibraryGenerateCurlUrls,
// generates a fresh Authorization Bearer token per object, and runs
// the curl download commands with optional concurrency.
// FORMATTED FOR WINDOWS POWERSHELL

const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");

const { NewOpt } = require("./lib/options");
const Utility = require("./lib/Utility");

const FabricObject = require("./lib/concerns/FabricObject");

class BatchDownloadFromJson extends Utility {
    blueprint() {
        return {
            concerns: [FabricObject],
            options: [
                NewOpt("input", {
                    descTemplate: "Path to JSON file containing array of objects from LibraryGenerateCurlUrls",
                    demand: true,
                    normalize: true,
                    type: "string",
                }),
                NewOpt("downloadDir", {
                    descTemplate: "Directory to save downloaded files (default: current directory)",
                    normalize: true,
                    type: "string",
                }),
                NewOpt("concurrent", {
                    default: 1,
                    descTemplate: "Number of concurrent downloads to run at the same time",
                    type: "number",
                }),
                NewOpt("failLog", {
                    descTemplate: "Path to JSON file to write failed downloads to (object_id + error)",
                    normalize: true,
                    type: "string",
                }),
                NewOpt("downloaded", {
                    descTemplate: "Path to JSON file to write successful downloads to (object_id + filename)",
                    normalize: true,
                    type: "string",
                }),
            ],
        };
    }

    header() {
        return "Batch download objects from JSON using curl";
    }

    runCurl(curlBin, curlArgs, label) {
        return new Promise((resolve) => {
            this.logger.log(`Starting: ${label}`);

            // Spawn curl directly without a shell so %{...} in --write-out is
            // passed to curl as-is and not expanded by cmd.exe on Windows
            const child = spawn(curlBin, curlArgs, {
                stdio: ["ignore", "pipe", "ignore"],
            });

            let writeOut = "";
            child.stdout.on("data", chunk => writeOut += chunk.toString());

            child.on("close", (code) => {
                if (code === 0) {
                    const [sizeDownload, contentLength] = writeOut.trim().split("\n").map(Number);
                    if (contentLength > 0 && sizeDownload !== contentLength) {
                        const error = `Incomplete download: received ${sizeDownload} of ${contentLength} bytes`;
                        this.logger.error(`✘ ${error}: ${label}`);
                        resolve({ label, success: false, error });
                    } else {
                        this.logger.log(`✔ Done: ${label}`);
                        resolve({ label, success: true });
                    }
                } else {
                    this.logger.error(`✘ Failed (exit ${code}): ${label}`);
                    resolve({ label, success: false, exitCode: code });
                }
            });

            child.on("error", (err) => {
                this.logger.error(`✘ Error spawning curl for ${label}: ${err.message}`);
                resolve({ label, success: false, error: err.message });
            });
        });
    }

    finalize(tmpPath, finalPath, label) {
        const stat = fs.existsSync(tmpPath) ? fs.statSync(tmpPath) : null;
        if (!stat || stat.size === 0) {
            this.logger.error(`✘ Empty or missing tmp file, leaving as-is: ${tmpPath}`);
            return false;
        }
        fs.renameSync(tmpPath, finalPath);
        this.logger.log(`✔ Saved: ${label}`);
        return true;
    }

    appendFailEntry(failLogPath, entry) {
        let entries = [];
        if (fs.existsSync(failLogPath)) {
            try {
                entries = JSON.parse(fs.readFileSync(failLogPath, "utf8"));
            } catch {
                // malformed — start fresh
            }
        }
        entries.push(entry);
        fs.writeFileSync(failLogPath, JSON.stringify(entries, null, 2));
    }

    async body() {
        const inputPath = path.resolve(this.args.input);
        const concurrent = Math.max(1, this.args.concurrent || 1);
        const downloadDir = this.args.downloadDir
            ? path.resolve(this.args.downloadDir)
            : process.cwd();

        if (!fs.existsSync(inputPath))
            throw new Error(`Input file not found: ${inputPath}`);

        if (!fs.existsSync(downloadDir))
            fs.mkdirSync(downloadDir, { recursive: true });

        const objects = JSON.parse(fs.readFileSync(inputPath, "utf8"));
        if (!Array.isArray(objects))
            throw new Error("Input JSON must be an array of objects");

        // Filter out objects with errors
        const skipped = objects.filter(o => o.error);
        const valid = objects.filter(o => !o.error);

        if (skipped.length > 0) {
            this.logger.warn(`Skipping ${skipped.length} object(s) with errors:`);
            for (const o of skipped)
                this.logger.warn(`  - ${o.name || o.object_id}: ${o.error}`);
        }

        this.logger.log(`\nProcessing ${valid.length} object(s) with concurrency=${concurrent}\n`);

        const failLogPath = this.args.failLog ? path.resolve(this.args.failLog) : null;

        const client = await this.concerns.Client.get();
        const results = [];

        // Queue holds raw object data — tokens are generated per-job right before each curl runs
        const jobs = valid.map(obj => ({
            objectId: obj.object_id,
            name: obj.name,
            filename: obj.filename,
            downloadUrl: obj.download_url,
            curlTemplate: obj.curl,
        }));

        // Concurrency pool — always keeps exactly `concurrent` downloads running.
        // When one finishes, the next job from the queue is immediately started.
        let jobIndex = 0;

        const runNext = async () => {
            if (jobIndex >= jobs.length) return;
            const job = jobs[jobIndex++];
            const { objectId, name, filename, downloadUrl, curlTemplate } = job;

            try {
                // Generate a fresh token immediately before this curl runs
                const versionHash = await this.concerns.FabricObject.latestVersionHash({ objectId });

                const token = await client.CreateSignedToken({
                    versionHash,
                    duration: 5 * 24 * 60 * 60 * 1000, // 5 days in milliseconds
                });

                const outputPath = path.join(downloadDir, filename);
                const tmpPath = outputPath + ".tmp";

                // Fill token into the JSON curl — used only for fail log logging
                const curlCmd = curlTemplate.replace('Bearer "', `Bearer ${token}"`);

                // Spawn curl directly (no shell) so paths and --write-out are
                // passed as-is regardless of Windows cmd.exe or PowerShell
                const curlBin = process.platform === "win32" ? "curl.exe" : "curl";
                const curlArgs = [
                    "-L",
                    "--fail",
                    "-o", tmpPath,
                    "--write-out", "%{size_download}\n%{content_length}",
                    downloadUrl,
                    "-H", `Authorization: Bearer ${token}`,
                ];

                const result = await this.runCurl(curlBin, curlArgs, filename);

                if (result.success) {
                    result.success = this.finalize(tmpPath, outputPath, filename);
                    if (!result.success) result.error = "incomplete download (empty tmp file)";
                }

                results.push({ ...result, object_id: objectId, name, label: filename });

                if (!result.success && failLogPath) {
                    this.appendFailEntry(failLogPath, {
                        object_id: objectId,
                        name,
                        download_url: downloadUrl,
                        curl_cmd: curlCmd,
                        error_type: "curl_failure",
                        error: result.error || `curl exited with code ${result.exitCode}`,
                    });
                }
            } catch (err) {
                this.logger.error(`Failed to generate token for ${objectId}: ${err.message}`);
                results.push({ object_id: objectId, name, label: filename, success: false, error: err.message });

                if (failLogPath) {
                    this.appendFailEntry(failLogPath, {
                        object_id: objectId,
                        name,
                        download_url: downloadUrl,
                        error_type: "token_failure",
                        error: err.message,
                    });
                }
            }

            // As soon as this slot is free, pull the next job
            await runNext();
        };

        // Seed exactly `concurrent` workers; each self-replenishes until the queue is empty
        const workers = Array.from(
            { length: Math.min(concurrent, jobs.length) },
            () => runNext()
        );
        await Promise.all(workers);

        const succeeded = results.filter(r => r.success);
        const failed = results.filter(r => !r.success);

        // Write --downloaded log
        if (this.args.downloaded) {
            const downloadedPath = path.resolve(this.args.downloaded);
            const downloadedEntries = succeeded.map(r => ({ object_id: r.object_id, name: r.name, filename: r.label }));
            fs.writeFileSync(downloadedPath, JSON.stringify(downloadedEntries, null, 2));
            this.logger.log(`Downloaded log written to ${downloadedPath}`);
        }

        if (failLogPath && failed.length > 0)
            this.logger.log(`Fail log written to ${failLogPath}`);

        // Summary
        this.logger.log("\n=== SUMMARY ===");
        this.logger.log(`Skipped:    ${skipped.length}`);
        this.logger.log(`Successful: ${succeeded.length}`);
        this.logger.log(`Failed:     ${failed.length}`);

        return results;
    }
}

if (require.main === module) {
    Utility.cmdLineInvoke(BatchDownloadFromJson);
} else {
    module.exports = BatchDownloadFromJson;
}
