// Reads a JSON file of objects generated by LibraryGenerateCurlUrls,
// generates a fresh Authorization Bearer token per object, and runs
// the curl download commands with optional concurrency.
// FORMATTED FOR WINDOWS POWERSHELL

const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");

const { NewOpt } = require("./lib/options");
const Utility = require("./lib/Utility");

const FabricObject = require("./lib/concerns/FabricObject");

class BatchDownloadFromJson extends Utility {
    blueprint() {
        return {
            concerns: [FabricObject],
            options: [
                NewOpt("input", {
                    descTemplate: "Path to JSON file containing array of objects from LibraryGenerateCurlUrls",
                    demand: true,
                    normalize: true,
                    type: "string",
                }),
                NewOpt("downloadDir", {
                    descTemplate: "Directory to save downloaded files (default: current directory)",
                    normalize: true,
                    type: "string",
                }),
                NewOpt("concurrent", {
                    default: 1,
                    descTemplate: "Number of concurrent downloads to run at the same time",
                    type: "number",
                }),
                NewOpt("failLog", {
                    descTemplate: "Path to JSON file to write failed downloads to (object_id + error)",
                    normalize: true,
                    type: "string",
                }),
                NewOpt("downloaded", {
                    descTemplate: "Path to JSON file to write successful downloads to (object_id + filename)",
                    normalize: true,
                    type: "string",
                }),
            ],
        };
    }

    header() {
        return "Batch download objects from JSON using curl";
    }

    runCurl(curlCmd, label) {
        return new Promise((resolve) => {
            this.logger.log(`Starting: ${label}`);

            // Use -s (silent) to suppress curl's progress meter, and pipe stdio
            // so concurrent processes don't fight over the terminal and stall each other
            const child = spawn(curlCmd + " -s", {
                shell: true,
                stdio: ["ignore", "pipe", "pipe"],
            });

            child.on("close", (code) => {
                if (code === 0) {
                    this.logger.log(`✔ Done: ${label}`);
                    resolve({ label, success: true });
                } else {
                    this.logger.error(`✘ Failed (exit ${code}): ${label}`);
                    resolve({ label, success: false, exitCode: code });
                }
            });

            child.on("error", (err) => {
                this.logger.error(`✘ Error spawning curl for ${label}: ${err.message}`);
                resolve({ label, success: false, error: err.message });
            });
        });
    }

    async body() {
        const inputPath = path.resolve(this.args.input);
        const concurrent = Math.max(1, this.args.concurrent || 1);
        const downloadDir = this.args.downloadDir
            ? path.resolve(this.args.downloadDir)
            : process.cwd();

        if (!fs.existsSync(inputPath))
            throw new Error(`Input file not found: ${inputPath}`);

        if (!fs.existsSync(downloadDir))
            fs.mkdirSync(downloadDir, { recursive: true });

        const objects = JSON.parse(fs.readFileSync(inputPath, "utf8"));
        if (!Array.isArray(objects))
            throw new Error("Input JSON must be an array of objects");

        // Filter out objects with errors
        const skipped = objects.filter(o => o.error);
        const valid = objects.filter(o => !o.error);

        if (skipped.length > 0) {
            this.logger.warn(`Skipping ${skipped.length} object(s) with errors:`);
            for (const o of skipped)
                this.logger.warn(`  - ${o.name || o.object_id}: ${o.error}`);
        }

        this.logger.log(`\nProcessing ${valid.length} object(s) with concurrency=${concurrent}\n`);

        const client = await this.concerns.Client.get();
        const results = [];

        // Queue holds raw object data — tokens are generated per-job right before each curl runs
        const jobs = valid.map(obj => ({
            objectId: obj.object_id,
            name: obj.name,
            versionHash: obj.version_hash,
            filename: obj.filename,
            downloadUrl: obj.download_url,
        }));

        // Concurrency pool — always keeps exactly `concurrent` downloads running.
        // When one finishes, the next job from the queue is immediately started.
        let jobIndex = 0;

        const runNext = async () => {
            if (jobIndex >= jobs.length) return;
            const job = jobs[jobIndex++];
            const { objectId, name, versionHash, filename, downloadUrl } = job;

            try {
                // Generate a fresh token immediately before this curl runs
                const versionHash = await this.concerns.FabricObject.latestVersionHash({ objectId });

                const token = await client.CreateSignedToken({
                    versionHash,
                    duration: 5 * 24 * 60 * 60 * 1000, // 5 days in milliseconds
                });

                const outputPath = path.join(downloadDir, filename);
                const psUrl = downloadUrl.replace(/@/g, "`@");
                const curlCmd = `curl.exe -o "${outputPath}" "${psUrl}" -H "Authorization: Bearer ${token}"`;

                const result = await this.runCurl(curlCmd, filename);
                results.push({ ...result, object_id: objectId, name, label: filename });
            } catch (err) {
                this.logger.error(`Failed to generate token for ${objectId}: ${err.message}`);
                results.push({ object_id: objectId, name, label: filename, success: false, error: err.message });
            }

            // As soon as this slot is free, pull the next job
            await runNext();
        };

        // Seed exactly `concurrent` workers; each self-replenishes until the queue is empty
        const workers = Array.from(
            { length: Math.min(concurrent, jobs.length) },
            () => runNext()
        );
        await Promise.all(workers);

        const succeeded = results.filter(r => r.success);
        const failed = results.filter(r => !r.success);

        // Write --downloaded log
        if (this.args.downloaded) {
            const downloadedPath = path.resolve(this.args.downloaded);
            const downloadedEntries = succeeded.map(r => ({ object_id: r.object_id, name: r.name, filename: r.label }));
            fs.writeFileSync(downloadedPath, JSON.stringify(downloadedEntries, null, 2));
            this.logger.log(`Downloaded log written to ${downloadedPath}`);
        }

        // Write --failLog log
        if (this.args.failLog) {
            const failLogPath = path.resolve(this.args.failLog);
            const failEntries = failed.map(r => ({
                object_id: r.object_id,
                name: r.name,
                error: r.error || `curl exited with code ${r.exitCode}`,
            }));
            fs.writeFileSync(failLogPath, JSON.stringify(failEntries, null, 2));
            this.logger.log(`Fail log written to ${failLogPath}`);
        }

        // Summary
        this.logger.log("\n=== SUMMARY ===");
        this.logger.log(`Skipped:    ${skipped.length}`);
        this.logger.log(`Successful: ${succeeded.length}`);
        this.logger.log(`Failed:     ${failed.length}`);

        return results;
    }
}

if (require.main === module) {
    Utility.cmdLineInvoke(BatchDownloadFromJson);
} else {
    module.exports = BatchDownloadFromJson;
}
